name: Model Architecture & Training

on: [push]

jobs:
  model_pipeline:
    runs-on: ubuntu-24.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision torchsummary
        
    - name: Run Model Pipeline
      id: pipeline
      run: |
        echo "Running Model Architecture Tests..."
        python test_model.py
        
        echo "\nStarting Model Training..."
        python train.py
        
    - name: Upload training logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: training-logs
        path: training.log
        retention-days: 90
        
    - name: Upload best model
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: best-model
        path: best_model.pth
        retention-days: 90

    - name: Update README badge
      if: always()
      run: |
        if [ $? -eq 0 ]; then
          sed -i 's/ML%20Pipeline-.*-success/ML%20Pipeline-Active-success/' README.md
        else
          sed -i 's/ML%20Pipeline-.*-success/ML%20Pipeline-Failed-red/' README.md
        fi
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update ML Pipeline badge status" || echo "No changes to commit"
        git push || echo "No changes to push" 